export const ROLES = { CUSTOMER: 'CUSTOMER', TECHNICAL: 'TECHNICAL', ADMIN: 'ADMIN' };
export const USER_STATUS = { ACTIVE: 'ACTIVE', SUSPENDED: 'SUSPENDED', DISABLED: 'DISABLED', DELETED: 'DELETED' };
export const PAYMENT_STATUS = { PENDING: 'PENDING', APPROVED: 'APPROVED', REJECTED: 'REJECTED', GAPPED: 'GAPPED' };
export const ORDER_STATUS = { PENDING: 'PENDING', CONFIRMED: 'CONFIRMED', PROCESSING: 'PROCESSING', COMPLETED: 'COMPLETED', CANCELLED: 'CANCELLED', SUSPENDED: 'SUSPENDED' };
export const SHIPPING_STATUS = { NOT_SHIPPED: 'NOT_SHIPPED', PREPARING: 'PREPARING', SHIPPED: 'SHIPPED', OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY', DELIVERED: 'DELIVERED', RETURNED: 'RETURNED' };
export const EXPENSE_TYPE = { MATERIALISTIC: 'MATERIALISTIC', OPERATIONAL: 'OPERATIONAL' };
